# Config file for automatic testing at travis-ci.org
sudo: false

language: python

cache: pip

python: 3.6

matrix:
  fast_finish: true

# Addons
addons:
  postgresql: '9.6'
  sonarcloud:
    organization: "openexo"
    token:
      secure: "cgqkk7FMlbw+1N03PZJA2NSE/HvDQT/l60w+yy5xOuDtS2rqxm7WWTeL9PbWF8NAptNZ4sS/NhOKdu8ngkosNRPByzNiMWNLUaaFUmBuXQj8JGxW7kZbKJSiXhno8SaKh/qa2ZiWelpLSMiK5OBVmWeGRxsmvpHDMEentnAu6IPwYWnVl54K+18MW6mHb7C0Y7dqt88cwr+HLbZzEwccgZF5iwrKr1oXlA36M/S9+BxQz/9qKIVydn3bTZlyvnHzmkQsDNIl0ZJrhBWNbtrTsgJQmXsesdtnaNDX7yv7Uk+tXscA1zAVIXIBTVnXBh6VCFjHM+0rAgmSsghsPMAE5WVpForoIgRsDVvaedlgqEvX5IhbDMsTL9y4D/eLK65IznlPaU1YM8zp/pk5w8OpjVOYqZ+SoE+VQY/aWmwbdiBQnr9g1FO7L1GXF/XpM+rSp3gt/+hAz0u+w8JCuIb0akCLoHb7huoqErdPrIkBRnzDicN68t2zn4L49Fhk59L7qw2XeepgfOwx6Y18kVsJ/y/ggR8860CQyGwER6IplA2HDKY09xuq0TBDQGxmT9wvGQ1gswyw5d4oO4krNHlzMRy8+7TecNyV2PtGlP1sDoV+TPmmTaa4q2qE0GSgNw9cAjWWIuL+q+Fvf+g3/0X69nDv07U2LCZXIKu77YGKqls="

# install dependencies
install: pip install -r requirements_test.txt

# run tests on every Python version with tox
script: 
  - tox
  - sonar-scanner

# pypi deployment
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  twine_version: 1.13.0
  user: marfyl
  password: 
    secure: "BJBrMbhkfR82jHVlRR5z3u80qY5U3TSmRZqY++Ra4EZV1SiW3rf/aCRNo5p4mOnGRBqs4jTiCXHa4EtAMz7G0hWWFbhyjeTYkn/znm0MN/p8UwqnljgJATlV4s3tuAlqvqaD7c5SSmGzCm7okQcXhObQ9lRFVYRhQ2plQsuFlIrADjqe1yntG8ILolcURXjN4imMDHOBpsrE/WxRk/DpCYa84Oe6aAMYCe8+MF92zhziI/gN1/m0SE5KYYC/xX6FoNCVX3Zk56EnZ6ATIaqXVKY8fnT7gCBYIkEydEGxVCAyvBqmfHKYXiihJGdsqr1o7XwgdxGtBfcqS0dsNTXr+APRf8+lO6N58/07iQFhTJLgZV8RwjtUEeGXb4EqdhBCII5sOXucQgntpOic49aOpK9McBvcNok5V+BBMEIeChT1+uFAq1Cq8Hv2dx1ywoFs/qDSU9+PpWRLu5YlPnJGytpMMgVkvKp+XMhUoraZ1GgBKcQM62MAndHiPNzB2qJWbDXd5KRk2WJxDAHya0j2cB9pslQQitf291JX+hCABEjcJJzq5L31JkZR4Zr06sR1ohdoGOIRcdDDnaIKS/re5ypwUp4lN6SuhGgY+b1/Tv/s3OoSXJs+0SAMfWE69FTUh+tTcrKTSoAAMWM039YbRgYreiAK7BcKoVKs5FRML+4="
  on:
    tags: true
    repo: exolever/django-ratings-models
    python: 3.6

after_success:
  - codecov